cart/urls.py
from django.urls import path
from cart import views
from django.contrib.auth import views as auth_views
from cart.views import *

app_name = 'cart'
urlpatterns = [
    path('', CartListView.as_view(), name='list'),
    path('remove/<int:pk>/', CartDeleteView.as_view(), name='remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from member.views import *


urlpatterns = [
    path('', HotListView.as_view(), name='home'),
    path('jet/', include('jet.urls','jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# admin.sites.AdminSite.site_header = 'SHOP3 관리'
# admin.sites.AdminSite.site_title = 'SHOP3 관리'
# admin.sites.AdminSite.index_title = 'SHOP3 관리 HOME'   

order/urls.py
from django.urls import path
from order import views
from django.contrib.auth import views as auth_views
from order.views import *

app_name = 'order'
urlpatterns = [
    path('', OrderFormView.as_view(), name='orderview'),
    path('list', OrderListView.as_view(), name='list'),
    path('<int:pk>/', OrderDetailView.as_view(), name='detail'),
]

cart/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from product.models import Product
from django.contrib.auth.models import User
import os


class Cart(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField('가격')
    amount = models.IntegerField('수량')
    cartdate = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.id)
    
    def get_sum(self):
        return self.price * self.amount

cart/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from product.models import Product
from cart.models import Cart
from product.forms import AddProForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q


# 장바구니 목록
class CartListView(LoginRequiredMixin, ListView):
    login_url = '/member/login'
    template_name = 'cart/detail.html'

    def get_queryset(self):
        return Cart.objects.filter(author=self.request.user)

# 장바구니 삭제
class CartDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/member/login'
    model = Cart
    success_url = reverse_lazy('cart:list')

cart/templates/cart/cart_confirm_delete.html
{% extends "member/base.html" %}
{% block title %}
{% endblock %}
{% block content %}
<div class="card">
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            정말 삭제하시겠습니까?
            <input type="submit" value="삭제">
        </form>
    </div>
</div>
{% endblock %}
    

cart/templates/cart/detail.html
{% extends 'member/base.html' %}
{% load humanize %}
{% block title %}
{% endblock %}
{% block content %}
<div class="container my-4">
    <div class="card">
    <div class="card-body">
    <h3>장바구니</h3>
    <table class="table table-hover">
        <tr>
            <th>선택</th>
            <th>이미지</th>
            <th>상품명</th>
            <th>가격</th>
            <th>주문수량</th>
            <th>합계</th>
            <th>삭제</th>
        </tr>
        {% for cart in object_list %}
        <tr>
            <td>
                <input type="checkbox">
            </td>
            <td><img style="width:100px;height:100px;" src="{{cart.product.pro_img.url}}" class="img-thumbnail"></td>
            <td>{{cart.product.pro_name}}</td>
            <td>{{cart.price}}</td>
            <td>{{cart.amount}}</td>
            <td>{{cart.get_sum}}</td>
            <td><a href="{% url 'cart:remove' cart.id %}"><button type="button" class="btn btn-outline-primary">삭제</button></a></td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan=7>
            </td>
        </tr>
    </table>
    <div class="container" style="text-align:center;">
        <a href="{% url 'order:orderview' %}"><button type="button" class="btn btn-outline-primary">결제</button></a>
    </div>
    </div>
    </div>
</div>
{% endblock %}