cart/urls.py
from django.urls import path
from cart import views
from django.contrib.auth import views as auth_views
from cart.views import *

app_name = 'cart'
urlpatterns = [
    path('', CartListView.as_view(), name='list'),
    path('remove/<int:pk>/', CartDeleteView.as_view(), name='remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from member.views import *


urlpatterns = [
    path('', HotListView.as_view(), name='home'),
    path('jet/', include('jet.urls','jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# admin.sites.AdminSite.site_header = 'SHOP3 관리'
# admin.sites.AdminSite.site_title = 'SHOP3 관리'
# admin.sites.AdminSite.index_title = 'SHOP3 관리 HOME'   

product/urls.py
from django.urls import path
from product import views
from product.views import *

app_name = 'product'
urlpatterns = [
    path('', ProdListView.as_view(), name='list'),
    path('<int:pk>/', ProdDetailView.as_view(), name='detail'),
    path('like/',views.like, name='like'),
    #path('<int:product_id>', views.detail, name='detail'),
]

product/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

class Product(models.Model):
    pro_name = models.CharField('상품명',max_length=200)
    #pro_kind = models.IntegerField('상품종류', null=True)
    pro_status_choice = (
        ('f','Fruit'),
        ('p', 'Phone'),
        ('c', 'Computer'),
    )
    pro_status = models.CharField('카테고리', null=True, max_length=1, choices=pro_status_choice)
    pro_price = models.IntegerField('가격')
    pro_stock = models.IntegerField('재고수량',default=100)
    pro_img = models.ImageField('상품이미지', upload_to='products/%Y/%m/%d', blank=True)
    pro_desc = models.TextField('상품설명', blank=True)
    pro_hot = models.BooleanField('인기상품', default=False)
    pro_new = models.BooleanField('신규상품', default=False)
    pro_display = models.BooleanField('화면표시', default=True)
    pro_day = models.DateField('등록일', default=timezone.now)
    pro_like = models.IntegerField('좋아요', default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "상품관리"
        
    def __str__(self):
        return self.pro_name
        
    #def get_absolute_url(self):
        #return reverse('product:detail', args=[self.id])

product/forms.py
from django import forms
from cart.models import Cart
# 클라이언트 화면에 입력 폼을 만들어주려고
# 클라이언트가 입력한 데이터에 대한 전처리

class AddProForm(forms.Form):
    amount = forms.IntegerField(label='수량', initial=1,min_value=1)

class SearchForm(forms.Form):
    search_word = forms.CharField(max_length=100)

product/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from product.models import Product
from cart.models import Cart
from .forms import AddProForm
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
try:
    from django.utils import simplejson as json

except ImportError:
    import json


class ProdListView(ListView):
    model = Product
    template_name = 'product/list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(ProdListView, self).get_context_data(*args, **kwargs)
        context['search'] = self.request.GET.get('search')
        return context

    def get_queryset(self, *args, **kwargs):
        product_qs = super(ProdListView, self).get_queryset(*args, **kwargs)
        query = self.request.GET.get('search')

        if query :
            product_qs = self.model.objects.filter(Q(pro_name__contains=query))
        return product_qs


class ProdDetailView(LoginRequiredMixin, DetailView):
    login_url = '/member/login'
    model = Product
    template_name = 'product/detail.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['form'] = AddProForm()
        return context

    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, pk=self.kwargs['pk'])
        form_amount = AddProForm(request.POST)
        if form_amount.is_valid():
            cd = form_amount.cleaned_data
            try:
                cart = Cart.objects.get(Q(product_id=product.id) & Q(author=request.user))
            except (KeyError, Cart.DoesNotExist):
                qry = Cart(product_id=product.id, author=request.user, amount=cd['amount'], price=product.pro_price)
                qry.save()
            else:
                cart.price = product.pro_price
                cart.amount += cd['amount']
                cart.save()

            return HttpResponseRedirect(reverse('cart:list'))


def like(request):
    if request.method == 'POST':
        product_id = request.POST['pk']
        product = Product.objects.get(pk = product_id)
        product.pro_like +=1
        product.save()
        message = 'You liked this'

    context = {'likes_count' : product.pro_like, 'message' : message}

    return HttpResponse(json.dumps(context), content_type='application/json')

product/templates/product/detail.html
{% extends 'member/base.html' %}
{% load humanize %}
{% block content %}
<script>
    $(document).ready(function(){
        $('.like').click(function(){
            var pk = $(this).attr('name')
            $.ajax({	  
                url: "{% url 'product:like' %}",
                type: 'post',
                data: {
                    pk: pk, 
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(response){
                    $('#count'+ pk).html(response.likes_count);
                },
                error:function(xhr){
                    alert(xhr.status);
                }
            });
        })
    });
</script>
<div class="my-4">
    <div style="display:flex;justify-content:center;">
        <div class="mr-4">
            <img class="border" src="{{product.pro_img.url}}" style="width:300px;height:250px;">
        </div>
        <div style="width:30%;">
            <h3>{{product.pro_name}}</h3>
            {% if product.pro_hot == True %}    
                <span class="badge bg-danger text-light">인기상품</span>
            {% endif %}
            {% if product.pro_new == True %}
                <span class="badge bg-primary text-light">신규상품</span>
            {% endif %}<hr>
            {{product.pro_desc}}</br><hr>
            가격 : {{ product.pro_price|intcomma }}원</br><hr>
            재고수량 : {{ product.pro_stock}}</br><hr>
            등록일 : {{product.pro_day|date:'Y-m-d'}}</br><hr>
            <input type="button" class="like btn btn-outline-danger" name="{{product.id}}" value="좋아요">
            <span id="count{{product.id}}">{{product.pro_like}}</span></br><hr>

            <form id = "am_form"  method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-dark mb-3" value="장바구니 추가">
            </form>
            
        </div>
    </div>
</div>
{% endblock %}

product/templates/product/list.html
{% extends 'member/base.html' %}
{% load humanize %}
{% block title %} {% endblock %}
{% block content %}
<script>
    $(document).ready(function(){
        $(".col-4").on("click", function(){
            var a = $(this).attr("value");
            window.location.href=a;
        });
        $(".col-4").on("mouseover", function(){
            $(this).css("border","2px solid #4374D9");
        });
        $(".col-4").on("mouseout", function(){
            $(this).css("border","none");
        });
    });
</script>
<div class="container my-4">
    {% if search %}
    <h3>'{{ search }}' 검색결과</h3>
    {% else %}
    <h3>상품리스트</h3>
    {% endif %}
    <div class="row">
    {% for product in object_list %}
	    <div class="col-4" value="{{product.id}}">
		    <div class="card mb-3">
		        {% if product.pro_img %}
                <img style="height:200px;" class="img-fluid rounded-start" src="{{product.pro_img.url}}">
                {% endif %}
		        <div class="card-body">
		        <h5 class="card-title">
                    {{ product.pro_name }}
                    {% if product.pro_hot == True %}
                    <span class="badge bg-danger text-light">인기상품</span>
                    {% endif %}
                    {% if product.pro_new == True %}
                    <span class="badge bg-primary text-light">신규상품</span>
                    {% endif %}
                </h5>
                <p class="card-text">
                    가격 : {{ product.pro_price|intcomma }}원
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        재고 : {{ product.pro_stock }}개
                    </small>
                </p>
		        </div>
	        </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}