cart/urls.py
from django.urls import path
from cart import views
from django.contrib.auth import views as auth_views
from cart.views import *

app_name = 'cart'
urlpatterns = [
    path('', CartListView.as_view(), name='list'),
    path('remove/<int:pk>/', CartDeleteView.as_view(), name='remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from member.views import *


urlpatterns = [
    path('', HotListView.as_view(), name='home'),
    path('jet/', include('jet.urls','jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# admin.sites.AdminSite.site_header = 'SHOP3 관리'
# admin.sites.AdminSite.site_title = 'SHOP3 관리'
# admin.sites.AdminSite.index_title = 'SHOP3 관리 HOME'   

order/urls.py
from django.urls import path
from order import views
from django.contrib.auth import views as auth_views
from order.views import *

app_name = 'order'
urlpatterns = [
    path('', OrderFormView.as_view(), name='orderview'),
    path('list', OrderListView.as_view(), name='list'),
    path('<int:pk>/', OrderDetailView.as_view(), name='detail'),
]

cart/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from product.models import Product
from django.contrib.auth.models import User
import os


class Cart(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField('가격')
    amount = models.IntegerField('수량')
    cartdate = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.id)
    
    def get_sum(self):
        return self.price * self.amount

order/models.py
from django.db import models
from django.utils import timezone
from product.models import Product
from django.contrib.auth.models import User
# Create your models here.

class Order(models.Model):
    order_id = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    order_name = models.CharField('받는사람',max_length=200)
    order_tel = models.CharField('연락처', max_length=200)
    order_addr = models.CharField('주소', max_length=200)
    order_status_choice = [
        ('주문완료','주문완료'),
        ('결재완료','결재완료'),
        ('배송중','배송중'),
        ('배송완료','배송완료'),
        ('주문취소','주문취소'),
        ]
    order_status = models.CharField(max_length=20, choices=order_status_choice, default='주문완료')
    order_date = models.DateField('주문일', default=timezone.now)
    delivery = models.CharField('택배사', max_length=200, null=True, default='')
    delivery_no = models.CharField('송장번호', max_length=200, null=True, default='')
    
    class Meta:
        ordering = ['-order_date']

    def __str__(self):
        return self.order_id

    def get_total_product(self):
        return sum(item.get_item_price() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, related_name='order_products')
    price = models.IntegerField()
    amount = models.IntegerField()

    def __str__(self):
        return str(self.id)

    def get_item_price(self):
        return self.price * self.amount

order/forms.py
from django import forms

from .models import Order

class OrderAddForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['order_name', 'order_tel', 'order_addr']

order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from product.models import Product
from django.db.models import Q
from .forms import OrderAddForm
from cart.models import Cart
from order.models import Order, OrderItem
from datetime import datetime

class OrderListView(LoginRequiredMixin, ListView):
    login_url = '/member/login'
    template_name = 'order/list.html'

    def get_queryset(self):
        return Order.objects.filter(author=self.request.user)

class OrderDetailView(LoginRequiredMixin, DetailView):
    login_url = '/member/login'
    model = Order
    template_name = 'order/detail.html'

    #def get_queryset(self):
        #return self.queryset.filter(pk=self.kwargs['pk'])

class OrderFormView(FormView):
    form_class = OrderAddForm
    template_name = 'order/order.html'
    success_url = '/'

    def get_context_data(self, *args, **kwargs):
        cart_list = Cart.objects.filter(author=self.request.user)
        context = super(OrderFormView, self).get_context_data(**kwargs)
        context['cart_list'] = cart_list
        context['cart_total'] = sum(item.get_sum() for item in cart_list)

        return context 

    def form_valid(self, form):
        form_order = form.cleaned_data
        cart_list = Cart.objects.filter(author=self.request.user)
        today = datetime.now()
        order_id = today.strftime('%Y%m%d%H%M%S')

        order = Order(order_id=order_id, author=self.request.user, \
                        order_name=form_order['order_name'],\
                        order_tel=form_order['order_tel'],\
                        order_addr=form_order['order_addr'],\
                        delivery='로젠택배',\
                        delivery_no=today.strftime('%Y%m%d%H%M%S')+'78')
        order.save()

        for item in cart_list:
            OrderItem(order_id=order.id, product_id=item.product_id, price=item.price, \
                        amount=item.amount).save()
            ## 상품 테이블에 있는 재고수량을 감소
            decrement_stk = Product.objects.get(pk=item.product_id)
            decrement_stk.pro_stock -= item.amount
            decrement_stk.save()

        Cart.objects.filter(author=self.request.user).delete()

        return super(OrderFormView, self).form_valid(form)

order/templates/order/detail.html
{% extends 'member/base.html' %}
{% load humanize %}
{% block title %} 주문서 목록{% endblock %}

{% block content %}
<div class="container my-3">
<h2>주문상세</h2>
{{order.order_date|date:'Y-m-d'}}주문 | 주문번호 {{ order.order_id }}</br>
</br>
<div class="card my-3">
    <div class="card-body">
        <h3>배송정보</h3></hr>
        <table class="table table-condensed">
            <tr>
                <td>상태</td>
                <td>{{ order.order_status}}</td>
            </tr>
            <tr>
                <td>택배사</td>
                <td>{{ order.delivery }}</td>
            </tr>
            <tr>
                <td>송장번호</td>
                <td>{{ order.delivery_no}}</td>
            </tr>
        </table>
    </div>
</div>
<div class="card my-3">
    <div class="card-body">
        <h3>받는사람정보</h3></hr>
        <table class="table table-condensed">
            <tr>
                <td>받는사람</td>
                <td>{{ order.order_name }}</td>
            </tr>
            <tr>
                <td>연락처</td>
                <td>{{ order.order_tel}}</td>
            </tr>
            <tr>
                <td>받는주소</td>
                <td>{{ order.order_addr }}</td>
            </tr>
            <tr>
                <td class="ordertable1_last">요청사항</td>
                <td class="ordertable1_last">없음</td>
            </tr>
        </table>
    </div>
</div>
<div class="card my-3">
    <div class="card-body">
    <h3>상품목록</h3>
    <table class="table table-striped">
    <tr>
        <th scope="col">Image</th>
        <th scope="col">상품명</th>
        <th scope="col">가격</th>
        <th scope="col">주문수량</th>
        <th scope="col">총 가격</th>
        <th scope="col"></th>
    </tr>
    {% for item in order.items.all %}
    <tr>
        <td><img src="{{item.product.pro_img.url}}" class="img-thumbnail" width="100"></td>
        <td>{{item.product.pro_name}}</td>
        <td>{{item.product.pro_price}}</td>
        <td>{{item.amount}}</td>
        <td>{{item.get_item_price|intcomma}}원</td>
        <td></td>
    </tr>
    {% endfor %}
    <tr>
        <th colspan=6>
            주문 합계 : {{ order.get_total_product|intcomma}}원
        </th>
    </tr>
    </table>
    </div>
    </div>
</div>

{% endblock %}

order/templates/order/list.html
{% extends 'member/base.html' %}
{% load humanize %}
{% block title %}주문조회{% endblock %}

{% block content %}
<h3>{{ user.username }} 님의 주문 목록입니다.</h3>
<table class="table table-striped">
    <tr>
        <th></th>
        <th>주문번호</th>
        <th>주문일</th>
        <th>연락처</th>
        <th>배송지</th>
        <th>택배사</th>
        <th>송장번호</th>
        <th>상태</th>
        <th></th>
    </tr>
    {% for order in object_list %}
    <tr>
        <td>{{ order.id }}</td>
        <td><a href="#">{{ order.order_id }}</a></td>
        <td>{{ order.order_date|date:'Y-m-d' }}</td>
        <td>{{ order.order_tel }}</td>
        <td>{{ order.order_addr }}</td>
        <td>{{ order.delivery }}</td>
        <td>{{ order.delivery_no }}</td>
        <td>{{ order.order_status }}</td>
        <td><a href="{% url 'order:detail' order.id %}">[상세]</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

order/templates/order/order.html
{% extends 'member/base.html' %}
{% load humanize %}
{% block title %}주문서 작성{% endblock %}

{% block content %}
<div class="container my-3">
    <div class="card">
        <div class="card-body">
            <h3>상품결제</h3>
<div class="alert alert-info" role="alert"> {{user.username}}님의 배송 정보</div>
<form action="" method="post" class="order-form">
{{form.as_p}}
{% csrf_token %}
<div class="alert alert-info" role="alert">상품 목록</div>
<table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Product</th>
                <th scope="col">Quantity</th>
                <th scope="col">Unit Price</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart_list %}
				{% with product=item.product %}
                <tr>
                    <th scope="row">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{product.pro_img.url}}" class="img-thumbnail" width="100">
                        </a>
                    </th>
                    <td>{{product.pro_name}}</td>
                    <td>{{item.amount}}</td>
                    <td class="num">{{item.price|intcomma}}</td>
                    <td class="num">{{item.get_sum|intcomma}}</td>
                </tr>
				{% endwith %}
            {% endfor %}
		<tr class="total">
            <td>Total</td>
            <td colspan="2"></td>
            <td colspan="2" class="num"><div class="alert alert-success " role="alert">{{cart_total|intcomma}}</div></td>
        </tr>
        </tbody>
    </table>
<input type="submit" class="btn btn-danger btn-sm float-right" value="주문하기">
</form>
</div>
</div>
</div>
{% endblock %}