cart/urls.py
from django.urls import path
from cart import views
from django.contrib.auth import views as auth_views
from cart.views import *

app_name = 'cart'
urlpatterns = [
    path('', CartListView.as_view(), name='list'),
    path('remove/<int:pk>/', CartDeleteView.as_view(), name='remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from member.views import *


urlpatterns = [
    path('', HotListView.as_view(), name='home'),
    path('jet/', include('jet.urls','jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# admin.sites.AdminSite.site_header = 'SHOP3 관리'
# admin.sites.AdminSite.site_title = 'SHOP3 관리'
# admin.sites.AdminSite.index_title = 'SHOP3 관리 HOME'   

member/urls.py
from django.urls import path
from member import views
from django.contrib.auth import views as auth_views
from member.views import *

app_name = 'member'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='member/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

order/urls.py
from django.urls import path
from order import views
from django.contrib.auth import views as auth_views
from order.views import *

app_name = 'order'
urlpatterns = [
    path('', OrderFormView.as_view(), name='orderview'),
    path('list', OrderListView.as_view(), name='list'),
    path('<int:pk>/', OrderDetailView.as_view(), name='detail'),
]

product/urls.py
from django.urls import path
from product import views
from product.views import *

app_name = 'product'
urlpatterns = [
    path('', ProdListView.as_view(), name='list'),
    path('<int:pk>/', ProdDetailView.as_view(), name='detail'),
    path('like/',views.like, name='like'),
    #path('<int:product_id>', views.detail, name='detail'),
]

member/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField('주소', max_length=200)
    phone = models.CharField('전화번호', max_length=200)

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(author=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

member/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from member.models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['address', 'phone']

class UserForm(UserCreationForm):
    email=forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

member/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from member.forms import UserForm, ProfileForm
from product.models import Product
from member.models import Profile
from django.db import transaction

class HotListView(ListView):
    queryset = Product.objects.filter(pro_hot=True)
    template_name = 'member/index.html'


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            profile = profile_form.save(commit=False)
            profile.author = user
            profile.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)

            login(request, user)
            return redirect('home')
    else:
        form = UserForm()
        profile_form = ProfileForm()

    return render(request, 'member/signup.html', {'form':form, 'profile_form':profile_form})

member/templates/member/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}gittest2</title>
    <style>
        #div1 {
            background-color: #fafbfc;
            border: 15px solid;
            border-image: linear-gradient(to bottom, rgba(195, 195, 195, 0.75) , #fafbfc);
            border-image-slice: 100% 1 0 ;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
</head>
<body>
    {% include 'member/navbar.html' %}
    <div id="div1">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

member/templates/member/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
{% endif %}

member/templates/member/index.html
{% extends 'member/base.html' %}
{% load humanize %}
{% block title %}
{% endblock %}
{% block content %}
<script>
    $(document).ready(function(){
        $(".col-4").on("click", function(){
            var a = $(this).attr("value");
            window.location.href="product/"+a;
        });
        $(".col-4").on("mouseover", function(){
            $(this).css("border","2px solid #4374D9");
        });
        $(".col-4").on("mouseout", function(){
            $(this).css("border","none");
        });
    });
</script>
<div class="container my-4">
    <h3>인기상품</h3>
    <div class="row">
    {% for product in object_list %}
	    <div class="col-4" value="{{product.id}}">
		    <div class="card mb-3">
		        {% if product.pro_img %}
                <img style="height:200px;" class="img-fluid rounded-start" src="{{product.pro_img.url}}">
                {% endif %}
		        <div class="card-body">
		        <h5 class="card-title">
                    {{ product.pro_name }}
                    <span class="badge bg-danger text-light">인기상품</span>
                    {% if product.pro_new == True %}
                    <span class="badge bg-primary text-light">신규상품</span>
                    {% endif %}
                </h5>
                <p class="card-text">
                    가격 : {{ product.pro_price|intcomma }}원
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        재고 : {{ product.pro_stock }}개
                    </small>
                </p>
		        </div>
	        </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

member/templates/member/login.html
{% extends "member/base.html" %}
{% block content %}
<div class="container-lg my-3">
    <form method="POST" class="post-form" action="{% url 'member:login' %}">
        {% csrf_token %}
        {% include "member/form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:''}}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

member/templates/member/navbar.html
<nav style="background-color:#5872A5;" class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'home' %}">SHOP</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <span class="navbar-text"> {{user.username}}님이 로그인되었습니다.</span>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'account_logout' %}">로그아웃</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'cart:list' %}">장바구니</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'order:list' %}">주문목록</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'account_login' %}">로그인</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'member:signup' %}">회원가입</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'product:list' %}">상품</a>
            </li>
        </ul>
        <form class="d-flex mx-4" action="{% url 'product:list' %}"method="GET">
            <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
    </div>
</nav>

member/templates/member/signup.html
{% extends "member/base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는
                <a href="{% url 'member:login' %}">로그인 하세요.</a>
            </span>
        </div>
    </div>
    <form method="POST" class="post-form" action="{% url 'member:signup' %}">
        {% csrf_token %}
        {% include "member/form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username" value="{{form.username.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{form.username.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" value="{{form.password2.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email" value="{{form.email.value|default_if_none:''}}">
        </div>
        {{ profile_form }}
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}